dumpdata:
	python manage.py dumpdata piston --indent=4 > external_apps/piston/fixtures/initial_data.json
svn:
	svn update	
run:
	python manage.py runserver
sql:
	sqlite3 gulu.sqlite
migrate:
	python manage.py migrate
