python manage.py migrate deal
python manage.py migrate dish
python manage.py migrate gcomments
python manage.py migrate invite
python manage.py migrate photos
python manage.py migrate restaurant
python manage.py migrate review
python manage.py migrate user_profiles
python manage.py migrate wall
python manage.py migrate mission
python manage.py migrate locations
python manage.py migrate blog
python manage.py migrate recommend
python manage.py migrate ranking
